### ISSUE TITLE
Code does not compile with spring-hateoas 0.4.0 Snapshot

### ISSUE THREAD

**Issue by abhishekchavan** [dschulten/spring-hateoas-rest-service-sample#1]
I tried compiling the code with Spring Hateoas 0.4.0 Snapshot but it couldn't find some methods.

``` java
import static org.springframework.hateoas.mvc.ControllerLinkBuilder.linkToMethod;
import static org.springframework.hateoas.mvc.ControllerLinkBuilder.on;
import org.springframework.hateoas.ResourceDescriptor;
```

I checked the code repository for Spring Hateoas and the methods were not available in the classes.

**Comment by dschulten** [comment]
Hi,
Thank you for your interest. Those methods are only in my fork, Oliver did not accept my pull request yet. You need to mvn install the fork in order to get them. Maybe you want to vote for the pull if you like linkToMethod. This weekend I will check in improvements to the client, so if you like you might want to check again.
Best regards,
Dietrich

**Comment by ESTSky** [comment]
Hi,

I am trying to use methodOn method but it is only available on 0.4.0 Snapshot. It is not pulled yet. Do you know when your version will be available?

**Comment by dschulten** [comment]
Do you use linkTo(methodOn) or createFormFor(methodOn, name)? 

Only the latter has not been accepted yet. The former is on https://github.com/SpringSource/spring-hateoas/blob/master/src/main/java/org/springframework/hateoas/mvc/ControllerLinkBuilder.java. Or do you want to use it with jaxrs? Oliver did not add it for jaxrs yet.

Best regards
Dietrich

Gesendet von meinem ASUS Pad

**Comment by ESTSky** [comment]
In which release can I find createFormFor(methodOn, name) ? I have the 0.3.0.RELEASE version at the moment, and I still can not see createFormFor method.

**Comment by dschulten** [comment]
I see. Thank you for your interest! Oliver accepted linkto(methodon()) in 0.4.0-snapshot and the form creation is in pull request #38, which has not been accepted yet. 

## You must checkout my fork of spring-hateoas and build it if you want to try it out. See SamplePersonController and HtmlFormResourceMessageConverter for usage examples. 

Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.

ESTSky notifications@github.com schrieb:

In which release can I find createFormFor(methodOn, name) ? I have the 0.3.0.RELEASE version at the moment, and I still can not see createFormFor method.

**Comment by lshoo** [comment]
When the 0.4.0  can m1 and release?
Thanks!

**Comment by dschulten** [comment]
Please ask this question on the corresponding issue,  https://github.com/SpringSource/spring-hateoas/issues/19,  I'm not the one who decides this.
